import "./globals.css";
import type { Metadata } from "next";

// import components
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cocktails",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="p-5">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
